In [1]:
import numpy as np
import os
import pandas as pd

In [2]:
gtf_fn = "/groups/cgsd/xianjie/data/refseq/refdata-cellranger-GRCh38-3.0.0/genes/genes.gtf"
out_dir = "../"

In [3]:
def extract_genes(fn, out_fn):
    in_fp = open(fn, "r")
    out_fp = open(out_fn, "w")
    
    header = "\t".join(["gene_id", "chrom", "start", "end", "strand", "gene_name", "hgnc_id", "gene_type"])
    out_fp.write(header + "\n")
    
    nl = 0
    for line in in_fp:
        nl += 1
        if line.startswith("#"):
            continue
        items = line.strip().split("\t")
        if len(items) != 9:
            print("[E] n_fields != 9 in line %d." % nl)
            break
        chrom, source, biotype, start, end, score, strand, frame, attribute = items[:9]
        if biotype != "gene":
            continue
        if strand not in ("+", "-"):
            print("[E] invalid strand '%s' in line %d." % (strand, nl))
            break
        attr_list = [attr.strip() for attr in attribute.split(";") if len(attr) > 0]
        gene_id = gene_name = gene_type = hgnc_id = ""
        for attr in attr_list:
            items_attr = [s.strip('"') for s in attr.split(" ") if len(s) > 0]
            if len(items_attr) != 2:
                print("[E] invalid attribute in line %d." % nl)
            key, value = items_attr[:2]
            if key == "gene_id":
                gene_id = value
            elif key == "gene_name":
                gene_name = value
            elif key == "gene_biotype":
                gene_type = value
            elif key == "hgnc_id":
                hgnc_id = value
        rec = "\t".join([gene_id, chrom, start, end, strand, gene_name, hgnc_id, gene_type])
        out_fp.write(rec + "\n")
        
    in_fp.close()
    out_fp.close()

In [4]:
tsv_fn = os.path.join(out_dir, "refdata-cellranger-GRCh38-3.0.0.all.8column.genes.unsort.tsv")
extract_genes(gtf_fn, tsv_fn)

In [5]:
dat = pd.read_csv(tsv_fn, sep = "\t")
dat

,gene_id,chrom,start,end,strand,gene_name,hgnc_id,gene_type
0,ENSG00000243485,1,29554,31109,+,MIR1302-2HG,NaN,lincRNA
1,ENSG00000237613,1,34554,36081,-,FAM138A,NaN,lincRNA
2,ENSG00000186092,1,65419,71585,+,OR4F5,NaN,protein_coding
3,ENSG00000238009,1,89295,133723,-,AL627309.1,NaN,lincRNA
4,ENSG00000239945,1,89551,91105,-,AL627309.3,NaN,lincRNA
...,...,...,...,...,...,...,...,...
33533,ENSG00000277856,KI270726.1,26241,26534,+,AC233755.2,NaN,protein_coding
33534,ENSG00000275063,KI270726.1,41444,41876,+,AC233755.1,NaN,protein_coding
33535,ENSG00000271254,KI270711.1,4612,29626,-,AC240274.1,NaN,protein_coding
33536,ENSG00000277475,KI270713.1,31698,32528,-,AC213203.1,NaN,protein_coding
33537,ENSG00000268674,KI270713.1,35407,35916,+,FAM231C,NaN,protein_coding

### Check N.A.

In [6]:
for column in dat.columns:
    n_na = np.sum(dat[column].isna())
    print(column, n_na)

gene_id 0
chrom 0
start 0
end 0
strand 0
gene_name 0
hgnc_id 33538
gene_type 0

### Check order

In [7]:
uniq_chroms = np.unique(dat["chrom"])
for chrom in uniq_chroms:
    start = dat["start"][dat["chrom"] == chrom].values
    if len(start) == 1:
        print(chrom, 1, True)
    start_pre = start[:-1]
    start_next = start[1:]
    is_sorted = np.all(start_pre <= start_next)
    print(chrom, len(start), is_sorted)

1 3154 True
10 1230 True
11 1921 True
12 1765 True
13 666 True
14 1385 True
15 1135 True
16 1531 True
17 1894 True
18 662 True
19 2004 True
2 2285 True
20 895 True
21 502 True
22 837 True
3 1719 True
4 1353 True
5 1661 True
6 1632 True
7 1539 True
8 1320 True
9 1228 True
GL000009.2 1 True
GL000009.2 1 True
GL000194.1 2 True
GL000195.1 2 True
GL000205.2 1 True
GL000205.2 1 True
GL000213.1 1 True
GL000213.1 1 True
GL000218.1 1 True
GL000218.1 1 True
GL000219.1 1 True
GL000219.1 1 True
KI270711.1 1 True
KI270711.1 1 True
KI270713.1 2 True
KI270721.1 1 True
KI270721.1 1 True
KI270726.1 2 True
KI270727.1 4 True
KI270728.1 6 True
KI270731.1 1 True
KI270731.1 1 True
KI270734.1 3 True
MT 13 True
X 1078 True
Y 100 True

### Check illegal characters in gene name

In [8]:
# 0-9   
# 'A' - 'Z'
# 'a' - 'z'
# '-', '.', '_'
legal_ascii_int = list(range(48, 58)) + \
    list(range(65, 91)) +  \
    list(range(97, 123)) + \
    [45, 46, 95]
legal_chars = set([chr(i) for i in legal_ascii_int])

In [9]:
def contains_any_illegal_chars(x, chars):
    illegal_chars = [s for s in x if s not in chars]
    return(len(illegal_chars) > 0)

In [10]:
flag = dat[["gene_name"]].map(contains_any_illegal_chars, chars = legal_chars).values
dat[flag]

Empty DataFrame
Columns: [gene_id, chrom, start, end, strand, gene_name, hgnc_id, gene_type]
Index: []

In [11]:
dat = dat[~flag]
dat

,gene_id,chrom,start,end,strand,gene_name,hgnc_id,gene_type
0,ENSG00000243485,1,29554,31109,+,MIR1302-2HG,NaN,lincRNA
1,ENSG00000237613,1,34554,36081,-,FAM138A,NaN,lincRNA
2,ENSG00000186092,1,65419,71585,+,OR4F5,NaN,protein_coding
3,ENSG00000238009,1,89295,133723,-,AL627309.1,NaN,lincRNA
4,ENSG00000239945,1,89551,91105,-,AL627309.3,NaN,lincRNA
...,...,...,...,...,...,...,...,...
33533,ENSG00000277856,KI270726.1,26241,26534,+,AC233755.2,NaN,protein_coding
33534,ENSG00000275063,KI270726.1,41444,41876,+,AC233755.1,NaN,protein_coding
33535,ENSG00000271254,KI270711.1,4612,29626,-,AC240274.1,NaN,protein_coding
33536,ENSG00000277475,KI270713.1,31698,32528,-,AC213203.1,NaN,protein_coding
33537,ENSG00000268674,KI270713.1,35407,35916,+,FAM231C,NaN,protein_coding

### Check duplicate gene names

In [12]:
dup = dat[dat["gene_name"].duplicated(keep = False)].copy()
dup

,gene_id,chrom,start,end,strand,gene_name,hgnc_id,gene_type
2230,ENSG00000143248,1,163111121,163321791,-,RGS5,NaN,protein_coding
2232,ENSG00000232995,1,163244505,163321894,-,RGS5,NaN,antisense
2997,ENSG00000285053,1,235328570,235448952,+,TBCE,NaN,protein_coding
2999,ENSG00000284770,1,235367360,235452443,+,TBCE,NaN,protein_coding
4798,ENSG00000128655,2,177623252,178072755,-,PDE11A,NaN,protein_coding
4799,ENSG00000284741,2,177628069,178108339,-,PDE11A,NaN,protein_coding
5435,ENSG00000237940,2,241970683,241977276,+,LINC01238,NaN,lincRNA
5438,ENSG00000261186,2,242087351,242088457,-,LINC01238,NaN,antisense
5832,ENSG00000283706,3,46712115,46717907,-,PRSS50,NaN,protein_coding
5833,ENSG00000206549,3,46712115,46812574,-,PRSS50,NaN,protein_coding
5949,ENSG00000114395,3,50350695,50358460,+,CYB561D2,NaN,protein_coding
5953,ENSG00000271858,3,50365334,50368197,+,CYB561D2,NaN,antisense
6093,ENSG00000285258,3,63864557,64003462,+,ATXN7,NaN,protein_coding
6094,ENSG00000163635,3,63898399,64003453,+,ATXN7,NaN,protein_coding
6461,ENSG00000283374,3,126571779,126608555,-,TXNRD3NB,NaN,protein_coding
6462,ENSG00000206483,3,126571789,126572636,-,TXNRD3NB,NaN,protein_coding
6915,ENSG00000284862,3,180602858,180679500,-,CCDC39,NaN,protein_coding
6916,ENSG00000145075,3,180614008,180870933,-,CCDC39,NaN,protein_coding
9595,ENSG00000280987,5,139273752,139331671,+,MATR3,NaN,protein_coding
9597,ENSG00000015479,5,139293648,139331677,+,MATR3,NaN,protein_coding
11683,ENSG00000112096,6,159669057,159745186,-,SOD2,NaN,protein_coding
11684,ENSG00000285441,6,159679119,159762529,-,SOD2,NaN,protein_coding
12718,ENSG00000168255,7,102537918,102572653,-,POLR2J3,NaN,protein_coding
12722,ENSG00000285437,7,102562133,102572583,-,POLR2J3,NaN,protein_coding
13263,ENSG00000285292,7,151207837,151227166,-,ABCF2,NaN,protein_coding
13264,ENSG00000033050,7,151212490,151227230,-,ABCF2,NaN,protein_coding
14005,ENSG00000158427,X,103918896,103966712,+,TMSB15B,NaN,protein_coding
14008,ENSG00000269226,X,104063871,104076212,-,TMSB15B,NaN,protein_coding
14540,ENSG00000258724,8,10725399,10839847,-,PINX1,NaN,protein_coding
14542,ENSG00000254093,8,10764963,10839884,-,PINX1,NaN,protein_coding
16455,ENSG00000234323,9,105993310,106740875,+,LINC01505,NaN,lincRNA
16459,ENSG00000234229,9,106664754,106702662,+,LINC01505,NaN,lincRNA
17071,ENSG00000284779,11,2129112,2158658,-,IGF2,NaN,protein_coding
17072,ENSG00000167244,11,2129112,2149603,-,IGF2,NaN,protein_coding
19042,ENSG00000284024,10,14838160,14847018,+,HSPA14,NaN,protein_coding
19043,ENSG00000187522,10,14838164,14871741,+,HSPA14,NaN,protein_coding
20257,ENSG00000126749,12,6970893,6979941,+,EMG1,NaN,protein_coding
20258,ENSG00000268439,12,6970921,6997428,+,EMG1,NaN,protein_coding
21710,ENSG00000284934,12,122207662,122227534,-,DIABLO,NaN,protein_coding
21711,ENSG00000184047,12,122207663,122226568,-,DIABLO,NaN,protein_coding
23965,ENSG00000280709,15,21552795,21653276,+,LINC02203,NaN,protein_coding
23966,ENSG00000284988,15,21552815,21557161,+,LINC02203,NaN,lincRNA
26223,ENSG00000213380,16,69320140,69339583,-,COG8,NaN,protein_coding
26224,ENSG00000272617,16,69326913,69339667,-,COG8,NaN,protein_coding
32973,ENSG00000130489,22,50523568,50525606,-,SCO2,NaN,protein_coding
32974,ENSG00000284194,22,50523568,50526439,-,SCO2,NaN,protein_coding
33006,ENSG00000274559,21,5972924,5973383,-,H2BFS,NaN,protein_coding
33393,ENSG00000234289,21,43565189,43565648,+,H2BFS,NaN,protein_coding

In [13]:
dat = dat[~dat["gene_name"].duplicated(keep = "first")]
dat

,gene_id,chrom,start,end,strand,gene_name,hgnc_id,gene_type
0,ENSG00000243485,1,29554,31109,+,MIR1302-2HG,NaN,lincRNA
1,ENSG00000237613,1,34554,36081,-,FAM138A,NaN,lincRNA
2,ENSG00000186092,1,65419,71585,+,OR4F5,NaN,protein_coding
3,ENSG00000238009,1,89295,133723,-,AL627309.1,NaN,lincRNA
4,ENSG00000239945,1,89551,91105,-,AL627309.3,NaN,lincRNA
...,...,...,...,...,...,...,...,...
33533,ENSG00000277856,KI270726.1,26241,26534,+,AC233755.2,NaN,protein_coding
33534,ENSG00000275063,KI270726.1,41444,41876,+,AC233755.1,NaN,protein_coding
33535,ENSG00000271254,KI270711.1,4612,29626,-,AC240274.1,NaN,protein_coding
33536,ENSG00000277475,KI270713.1,31698,32528,-,AC213203.1,NaN,protein_coding
33537,ENSG00000268674,KI270713.1,35407,35916,+,FAM231C,NaN,protein_coding

In [14]:
out_fn = os.path.join(out_dir, "refdata-cellranger-GRCh38-3.0.0.valid_name.uniq_name.8column.genes.unsort.tsv")
dat.to_csv(out_fn, sep = "\t", header = False, index = False)

### Subset genes in chr1-22,X,Y

In [15]:
chrom_list = ["%s" % i for i in range(1, 23)] + ["X", "Y"]
dat_subset = dat[dat["chrom"].isin(chrom_list)].copy()
dat_subset

,gene_id,chrom,start,end,strand,gene_name,hgnc_id,gene_type
0,ENSG00000243485,1,29554,31109,+,MIR1302-2HG,NaN,lincRNA
1,ENSG00000237613,1,34554,36081,-,FAM138A,NaN,lincRNA
2,ENSG00000186092,1,65419,71585,+,OR4F5,NaN,protein_coding
3,ENSG00000238009,1,89295,133723,-,AL627309.1,NaN,lincRNA
4,ENSG00000239945,1,89551,91105,-,AL627309.3,NaN,lincRNA
...,...,...,...,...,...,...,...,...
33491,ENSG00000160298,21,46300181,46323875,-,C21orf58,NaN,protein_coding
33492,ENSG00000160299,21,46324122,46445769,+,PCNT,NaN,protein_coding
33493,ENSG00000160305,21,46458899,46569852,+,DIP2A,NaN,protein_coding
33494,ENSG00000160307,21,46598962,46605208,-,S100B,NaN,protein_coding
33495,ENSG00000160310,21,46635167,46665124,+,PRMT2,NaN,protein_coding

In [16]:
dat_subset['chrom'] = pd.Categorical(dat_subset['chrom'], categories = chrom_list, ordered = True)
dat_subset = dat_subset.sort_values(by = ['chrom', 'start', 'end'])
dat_subset

,gene_id,chrom,start,end,strand,gene_name,hgnc_id,gene_type
0,ENSG00000243485,1,29554,31109,+,MIR1302-2HG,NaN,lincRNA
1,ENSG00000237613,1,34554,36081,-,FAM138A,NaN,lincRNA
2,ENSG00000186092,1,65419,71585,+,OR4F5,NaN,protein_coding
3,ENSG00000238009,1,89295,133723,-,AL627309.1,NaN,lincRNA
4,ENSG00000239945,1,89551,91105,-,AL627309.3,NaN,lincRNA
...,...,...,...,...,...,...,...,...
32152,ENSG00000228296,Y,25063083,25099892,-,TTTY4C,NaN,lincRNA
32153,ENSG00000223641,Y,25183643,25184773,-,TTTY17C,NaN,lincRNA
32154,ENSG00000228786,Y,25378300,25394719,-,LINC00266-4P,NaN,lincRNA
32155,ENSG00000172288,Y,25622162,25624902,+,CDY1,NaN,protein_coding
32156,ENSG00000231141,Y,25728490,25733388,+,TTTY3,NaN,lincRNA

In [17]:
out_fn = os.path.join(out_dir, "refdata-cellranger-GRCh38-3.0.0.valid_name.uniq_name.chrom1-22XY.5column.genes.tsv")
subset_columns = ["chrom", "start", "end", "gene_name", "strand"]
dat_subset[subset_columns].to_csv(out_fn, sep = "\t", header = False, index = False)

### Subset genes in chr1-22

In [18]:
chrom_list = ["%s" % i for i in range(1, 23)]
df = dat_subset[dat_subset["chrom"].isin(chrom_list)].copy()

df['chrom'] = pd.Categorical(df['chrom'], categories = chrom_list, ordered = True)
df = df.sort_values(by = ['chrom', 'start', 'end'])
df

,gene_id,chrom,start,end,strand,gene_name,hgnc_id,gene_type
0,ENSG00000243485,1,29554,31109,+,MIR1302-2HG,NaN,lincRNA
1,ENSG00000237613,1,34554,36081,-,FAM138A,NaN,lincRNA
2,ENSG00000186092,1,65419,71585,+,OR4F5,NaN,protein_coding
3,ENSG00000238009,1,89295,133723,-,AL627309.1,NaN,lincRNA
4,ENSG00000239945,1,89551,91105,-,AL627309.3,NaN,lincRNA
...,...,...,...,...,...,...,...,...
32989,ENSG00000251322,22,50674415,50733298,+,SHANK3,NaN,protein_coding
32990,ENSG00000225929,22,50735825,50738139,-,AC000036.1,NaN,antisense
32991,ENSG00000100312,22,50738196,50745334,+,ACR,NaN,protein_coding
32992,ENSG00000254499,22,50740593,50743520,-,AC002056.2,NaN,antisense
32993,ENSG00000079974,22,50767501,50783663,-,RABL2B,NaN,protein_coding

In [19]:
out_fn = os.path.join(out_dir, "refdata-cellranger-GRCh38-3.0.0.valid_name.uniq_name.chrom1-22.5column.genes.tsv")
subset_columns = ["chrom", "start", "end", "gene_name", "strand"]
df[subset_columns].to_csv(out_fn, sep = "\t", header = False, index = False)

In [20]:
out_fn = os.path.join(out_dir, "refdata-cellranger-GRCh38-3.0.0.valid_name.uniq_name.chrom1-22.4column.genes.tsv")
subset_columns = ["chrom", "start", "end", "gene_name"]
df[subset_columns].to_csv(out_fn, sep = "\t", header = False, index = False)